services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - postgres
    env_file:
      - config.env

  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=wallet_password
      - POSTGRES_DB=wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  postgres_data: